package cap.model;

public class Counter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column counter.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column counter.num
     *
     * @mbggenerated
     */
    private Long num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column counter.id
     *
     * @return the value of counter.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column counter.id
     *
     * @param id the value for counter.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column counter.num
     *
     * @return the value of counter.num
     *
     * @mbggenerated
     */
    public Long getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column counter.num
     *
     * @param num the value for counter.num
     *
     * @mbggenerated
     */
    public void setNum(Long num) {
        this.num = num;
    }
}