package cap.model;

import java.util.Date;

public class Ucomment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucomment.cid
     *
     * @mbggenerated
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucomment.cuid
     *
     * @mbggenerated
     */
    private Integer cuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucomment.artical_id
     *
     * @mbggenerated
     */
    private Integer articalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucomment.ccontent
     *
     * @mbggenerated
     */
    private String ccontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucomment.ctime
     *
     * @mbggenerated
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucomment.cdelete
     *
     * @mbggenerated
     */
    private Boolean cdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucomment.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucomment.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucomment.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucomment.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucomment.is_applied
     *
     * @mbggenerated
     */
    private Boolean isApplied;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucomment.udelete
     *
     * @mbggenerated
     */
    private Boolean udelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucomment.is_profile
     *
     * @mbggenerated
     */
    private Boolean isProfile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucomment.aid
     *
     * @mbggenerated
     */
    private Integer aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucomment.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucomment.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucomment.sys_category_id
     *
     * @mbggenerated
     */
    private Integer sysCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucomment.category_id
     *
     * @mbggenerated
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucomment.atime
     *
     * @mbggenerated
     */
    private Date atime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucomment.is_top
     *
     * @mbggenerated
     */
    private Boolean isTop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucomment.is_delete
     *
     * @mbggenerated
     */
    private Boolean isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucomment.cid
     *
     * @return the value of ucomment.cid
     *
     * @mbggenerated
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucomment.cid
     *
     * @param cid the value for ucomment.cid
     *
     * @mbggenerated
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucomment.cuid
     *
     * @return the value of ucomment.cuid
     *
     * @mbggenerated
     */
    public Integer getCuid() {
        return cuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucomment.cuid
     *
     * @param cuid the value for ucomment.cuid
     *
     * @mbggenerated
     */
    public void setCuid(Integer cuid) {
        this.cuid = cuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucomment.artical_id
     *
     * @return the value of ucomment.artical_id
     *
     * @mbggenerated
     */
    public Integer getArticalId() {
        return articalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucomment.artical_id
     *
     * @param articalId the value for ucomment.artical_id
     *
     * @mbggenerated
     */
    public void setArticalId(Integer articalId) {
        this.articalId = articalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucomment.ccontent
     *
     * @return the value of ucomment.ccontent
     *
     * @mbggenerated
     */
    public String getCcontent() {
        return ccontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucomment.ccontent
     *
     * @param ccontent the value for ucomment.ccontent
     *
     * @mbggenerated
     */
    public void setCcontent(String ccontent) {
        this.ccontent = ccontent == null ? null : ccontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucomment.ctime
     *
     * @return the value of ucomment.ctime
     *
     * @mbggenerated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucomment.ctime
     *
     * @param ctime the value for ucomment.ctime
     *
     * @mbggenerated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucomment.cdelete
     *
     * @return the value of ucomment.cdelete
     *
     * @mbggenerated
     */
    public Boolean getCdelete() {
        return cdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucomment.cdelete
     *
     * @param cdelete the value for ucomment.cdelete
     *
     * @mbggenerated
     */
    public void setCdelete(Boolean cdelete) {
        this.cdelete = cdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucomment.uid
     *
     * @return the value of ucomment.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucomment.uid
     *
     * @param uid the value for ucomment.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucomment.username
     *
     * @return the value of ucomment.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucomment.username
     *
     * @param username the value for ucomment.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucomment.password
     *
     * @return the value of ucomment.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucomment.password
     *
     * @param password the value for ucomment.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucomment.email
     *
     * @return the value of ucomment.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucomment.email
     *
     * @param email the value for ucomment.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucomment.is_applied
     *
     * @return the value of ucomment.is_applied
     *
     * @mbggenerated
     */
    public Boolean getIsApplied() {
        return isApplied;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucomment.is_applied
     *
     * @param isApplied the value for ucomment.is_applied
     *
     * @mbggenerated
     */
    public void setIsApplied(Boolean isApplied) {
        this.isApplied = isApplied;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucomment.udelete
     *
     * @return the value of ucomment.udelete
     *
     * @mbggenerated
     */
    public Boolean getUdelete() {
        return udelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucomment.udelete
     *
     * @param udelete the value for ucomment.udelete
     *
     * @mbggenerated
     */
    public void setUdelete(Boolean udelete) {
        this.udelete = udelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucomment.is_profile
     *
     * @return the value of ucomment.is_profile
     *
     * @mbggenerated
     */
    public Boolean getIsProfile() {
        return isProfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucomment.is_profile
     *
     * @param isProfile the value for ucomment.is_profile
     *
     * @mbggenerated
     */
    public void setIsProfile(Boolean isProfile) {
        this.isProfile = isProfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucomment.aid
     *
     * @return the value of ucomment.aid
     *
     * @mbggenerated
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucomment.aid
     *
     * @param aid the value for ucomment.aid
     *
     * @mbggenerated
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucomment.title
     *
     * @return the value of ucomment.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucomment.title
     *
     * @param title the value for ucomment.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucomment.user_id
     *
     * @return the value of ucomment.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucomment.user_id
     *
     * @param userId the value for ucomment.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucomment.sys_category_id
     *
     * @return the value of ucomment.sys_category_id
     *
     * @mbggenerated
     */
    public Integer getSysCategoryId() {
        return sysCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucomment.sys_category_id
     *
     * @param sysCategoryId the value for ucomment.sys_category_id
     *
     * @mbggenerated
     */
    public void setSysCategoryId(Integer sysCategoryId) {
        this.sysCategoryId = sysCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucomment.category_id
     *
     * @return the value of ucomment.category_id
     *
     * @mbggenerated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucomment.category_id
     *
     * @param categoryId the value for ucomment.category_id
     *
     * @mbggenerated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucomment.atime
     *
     * @return the value of ucomment.atime
     *
     * @mbggenerated
     */
    public Date getAtime() {
        return atime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucomment.atime
     *
     * @param atime the value for ucomment.atime
     *
     * @mbggenerated
     */
    public void setAtime(Date atime) {
        this.atime = atime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucomment.is_top
     *
     * @return the value of ucomment.is_top
     *
     * @mbggenerated
     */
    public Boolean getIsTop() {
        return isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucomment.is_top
     *
     * @param isTop the value for ucomment.is_top
     *
     * @mbggenerated
     */
    public void setIsTop(Boolean isTop) {
        this.isTop = isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucomment.is_delete
     *
     * @return the value of ucomment.is_delete
     *
     * @mbggenerated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucomment.is_delete
     *
     * @param isDelete the value for ucomment.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }
}