package cap.mapper;

import cap.model.UcommentWithBLOBs;

public interface UcommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucomment
     *
     * @mbggenerated
     */
    int insert(UcommentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucomment
     *
     * @mbggenerated
     */
    int insertSelective(UcommentWithBLOBs record);
}